/*
 * This file is generated by jOOQ.
 */
package com.yg.gqlwfdl.dataaccess.db;


import com.yg.gqlwfdl.dataaccess.db.tables.Company;
import com.yg.gqlwfdl.dataaccess.db.tables.CompanyPartnership;
import com.yg.gqlwfdl.dataaccess.db.tables.Customer;
import com.yg.gqlwfdl.dataaccess.db.tables.DiscountRate;
import com.yg.gqlwfdl.dataaccess.db.tables.PaymentMethod;
import com.yg.gqlwfdl.dataaccess.db.tables.PricingDetails;
import com.yg.gqlwfdl.dataaccess.db.tables.VatRate;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index COMPANY_PKEY = Indexes0.COMPANY_PKEY;
    public static final Index COMPANY_PARTNERSHIP_PKEY = Indexes0.COMPANY_PARTNERSHIP_PKEY;
    public static final Index CUSTOMER_PKEY = Indexes0.CUSTOMER_PKEY;
    public static final Index DISCOUNT_RATE_PKEY = Indexes0.DISCOUNT_RATE_PKEY;
    public static final Index PAYMENT_METHOD_PKEY = Indexes0.PAYMENT_METHOD_PKEY;
    public static final Index PRICING_DETAILS_PKEY = Indexes0.PRICING_DETAILS_PKEY;
    public static final Index VAT_RATE_PKEY = Indexes0.VAT_RATE_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index COMPANY_PKEY = Internal.createIndex("company_pkey", Company.COMPANY, new OrderField[] { Company.COMPANY.ID }, true);
        public static Index COMPANY_PARTNERSHIP_PKEY = Internal.createIndex("company_partnership_pkey", CompanyPartnership.COMPANY_PARTNERSHIP, new OrderField[] { CompanyPartnership.COMPANY_PARTNERSHIP.ID }, true);
        public static Index CUSTOMER_PKEY = Internal.createIndex("customer_pkey", Customer.CUSTOMER, new OrderField[] { Customer.CUSTOMER.ID }, true);
        public static Index DISCOUNT_RATE_PKEY = Internal.createIndex("discount_rate_pkey", DiscountRate.DISCOUNT_RATE, new OrderField[] { DiscountRate.DISCOUNT_RATE.ID }, true);
        public static Index PAYMENT_METHOD_PKEY = Internal.createIndex("payment_method_pkey", PaymentMethod.PAYMENT_METHOD, new OrderField[] { PaymentMethod.PAYMENT_METHOD.ID }, true);
        public static Index PRICING_DETAILS_PKEY = Internal.createIndex("pricing_details_pkey", PricingDetails.PRICING_DETAILS, new OrderField[] { PricingDetails.PRICING_DETAILS.ID }, true);
        public static Index VAT_RATE_PKEY = Internal.createIndex("vat_rate_pkey", VatRate.VAT_RATE, new OrderField[] { VatRate.VAT_RATE.ID }, true);
    }
}
