/*
 * This file is generated by jOOQ.
 */
package com.yg.gqlwfdl.dataaccess.db;


import com.yg.gqlwfdl.dataaccess.db.tables.Company;
import com.yg.gqlwfdl.dataaccess.db.tables.CompanyPartnership;
import com.yg.gqlwfdl.dataaccess.db.tables.Customer;
import com.yg.gqlwfdl.dataaccess.db.tables.DiscountRate;
import com.yg.gqlwfdl.dataaccess.db.tables.PaymentMethod;
import com.yg.gqlwfdl.dataaccess.db.tables.PricingDetails;
import com.yg.gqlwfdl.dataaccess.db.tables.VatRate;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -576843766;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.company</code>.
     */
    public final Company COMPANY = com.yg.gqlwfdl.dataaccess.db.tables.Company.COMPANY;

    /**
     * The table <code>public.company_partnership</code>.
     */
    public final CompanyPartnership COMPANY_PARTNERSHIP = com.yg.gqlwfdl.dataaccess.db.tables.CompanyPartnership.COMPANY_PARTNERSHIP;

    /**
     * The table <code>public.customer</code>.
     */
    public final Customer CUSTOMER = com.yg.gqlwfdl.dataaccess.db.tables.Customer.CUSTOMER;

    /**
     * The table <code>public.discount_rate</code>.
     */
    public final DiscountRate DISCOUNT_RATE = com.yg.gqlwfdl.dataaccess.db.tables.DiscountRate.DISCOUNT_RATE;

    /**
     * The table <code>public.payment_method</code>.
     */
    public final PaymentMethod PAYMENT_METHOD = com.yg.gqlwfdl.dataaccess.db.tables.PaymentMethod.PAYMENT_METHOD;

    /**
     * The table <code>public.pricing_details</code>.
     */
    public final PricingDetails PRICING_DETAILS = com.yg.gqlwfdl.dataaccess.db.tables.PricingDetails.PRICING_DETAILS;

    /**
     * The table <code>public.vat_rate</code>.
     */
    public final VatRate VAT_RATE = com.yg.gqlwfdl.dataaccess.db.tables.VatRate.VAT_RATE;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.COMPANY_ID_SEQ,
            Sequences.COMPANY_PARTNERSHIP_ID_SEQ,
            Sequences.CUSTOMER_ID_SEQ,
            Sequences.DISCOUNT_RATE_ID_SEQ,
            Sequences.PAYMENT_METHOD_ID_SEQ,
            Sequences.PRICING_DETAILS_ID_SEQ,
            Sequences.VAT_RATE_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Company.COMPANY,
            CompanyPartnership.COMPANY_PARTNERSHIP,
            Customer.CUSTOMER,
            DiscountRate.DISCOUNT_RATE,
            PaymentMethod.PAYMENT_METHOD,
            PricingDetails.PRICING_DETAILS,
            VatRate.VAT_RATE);
    }
}
