/*
 * This file is generated by jOOQ.
 */
package com.yg.gqlwfdl.dataaccess.db;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.company_id_seq</code>
     */
    public static final Sequence<Long> COMPANY_ID_SEQ = new SequenceImpl<Long>("company_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.company_partnership_id_seq</code>
     */
    public static final Sequence<Long> COMPANY_PARTNERSHIP_ID_SEQ = new SequenceImpl<Long>("company_partnership_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.customer_id_seq</code>
     */
    public static final Sequence<Long> CUSTOMER_ID_SEQ = new SequenceImpl<Long>("customer_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.discount_rate_id_seq</code>
     */
    public static final Sequence<Long> DISCOUNT_RATE_ID_SEQ = new SequenceImpl<Long>("discount_rate_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.order_id_seq</code>
     */
    public static final Sequence<Long> ORDER_ID_SEQ = new SequenceImpl<Long>("order_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.order_line_id_seq</code>
     */
    public static final Sequence<Long> ORDER_LINE_ID_SEQ = new SequenceImpl<Long>("order_line_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.payment_method_id_seq</code>
     */
    public static final Sequence<Long> PAYMENT_METHOD_ID_SEQ = new SequenceImpl<Long>("payment_method_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.pricing_details_id_seq</code>
     */
    public static final Sequence<Long> PRICING_DETAILS_ID_SEQ = new SequenceImpl<Long>("pricing_details_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.product_id_seq</code>
     */
    public static final Sequence<Long> PRODUCT_ID_SEQ = new SequenceImpl<Long>("product_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.vat_rate_id_seq</code>
     */
    public static final Sequence<Long> VAT_RATE_ID_SEQ = new SequenceImpl<Long>("vat_rate_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
