/*
 * This file is generated by jOOQ.
 */
package com.yg.gqlwfdl.dataaccess.db;


import com.yg.gqlwfdl.dataaccess.db.tables.Company;
import com.yg.gqlwfdl.dataaccess.db.tables.CompanyPartnership;
import com.yg.gqlwfdl.dataaccess.db.tables.Customer;
import com.yg.gqlwfdl.dataaccess.db.tables.DiscountRate;
import com.yg.gqlwfdl.dataaccess.db.tables.Order;
import com.yg.gqlwfdl.dataaccess.db.tables.OrderLine;
import com.yg.gqlwfdl.dataaccess.db.tables.PaymentMethod;
import com.yg.gqlwfdl.dataaccess.db.tables.PricingDetails;
import com.yg.gqlwfdl.dataaccess.db.tables.Product;
import com.yg.gqlwfdl.dataaccess.db.tables.VatRate;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.company</code>.
     */
    public static final Company COMPANY = com.yg.gqlwfdl.dataaccess.db.tables.Company.COMPANY;

    /**
     * The table <code>public.company_partnership</code>.
     */
    public static final CompanyPartnership COMPANY_PARTNERSHIP = com.yg.gqlwfdl.dataaccess.db.tables.CompanyPartnership.COMPANY_PARTNERSHIP;

    /**
     * The table <code>public.customer</code>.
     */
    public static final Customer CUSTOMER = com.yg.gqlwfdl.dataaccess.db.tables.Customer.CUSTOMER;

    /**
     * The table <code>public.discount_rate</code>.
     */
    public static final DiscountRate DISCOUNT_RATE = com.yg.gqlwfdl.dataaccess.db.tables.DiscountRate.DISCOUNT_RATE;

    /**
     * The table <code>public.order</code>.
     */
    public static final Order ORDER = com.yg.gqlwfdl.dataaccess.db.tables.Order.ORDER;

    /**
     * The table <code>public.order_line</code>.
     */
    public static final OrderLine ORDER_LINE = com.yg.gqlwfdl.dataaccess.db.tables.OrderLine.ORDER_LINE;

    /**
     * The table <code>public.payment_method</code>.
     */
    public static final PaymentMethod PAYMENT_METHOD = com.yg.gqlwfdl.dataaccess.db.tables.PaymentMethod.PAYMENT_METHOD;

    /**
     * The table <code>public.pricing_details</code>.
     */
    public static final PricingDetails PRICING_DETAILS = com.yg.gqlwfdl.dataaccess.db.tables.PricingDetails.PRICING_DETAILS;

    /**
     * The table <code>public.product</code>.
     */
    public static final Product PRODUCT = com.yg.gqlwfdl.dataaccess.db.tables.Product.PRODUCT;

    /**
     * The table <code>public.vat_rate</code>.
     */
    public static final VatRate VAT_RATE = com.yg.gqlwfdl.dataaccess.db.tables.VatRate.VAT_RATE;
}
