/*
 * This file is generated by jOOQ.
 */
package com.yg.gqlwfdl.dataaccess.db.tables;


import com.yg.gqlwfdl.dataaccess.db.Indexes;
import com.yg.gqlwfdl.dataaccess.db.Keys;
import com.yg.gqlwfdl.dataaccess.db.Public;
import com.yg.gqlwfdl.dataaccess.db.tables.records.PaymentMethodRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PaymentMethod extends TableImpl<PaymentMethodRecord> {

    private static final long serialVersionUID = 555873156;

    /**
     * The reference instance of <code>public.payment_method</code>
     */
    public static final PaymentMethod PAYMENT_METHOD = new PaymentMethod();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PaymentMethodRecord> getRecordType() {
        return PaymentMethodRecord.class;
    }

    /**
     * The column <code>public.payment_method.id</code>.
     */
    public final TableField<PaymentMethodRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('payment_method_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.payment_method.description</code>.
     */
    public final TableField<PaymentMethodRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.payment_method.charge</code>.
     */
    public final TableField<PaymentMethodRecord, Double> CHARGE = createField("charge", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * Create a <code>public.payment_method</code> table reference
     */
    public PaymentMethod() {
        this(DSL.name("payment_method"), null);
    }

    /**
     * Create an aliased <code>public.payment_method</code> table reference
     */
    public PaymentMethod(String alias) {
        this(DSL.name(alias), PAYMENT_METHOD);
    }

    /**
     * Create an aliased <code>public.payment_method</code> table reference
     */
    public PaymentMethod(Name alias) {
        this(alias, PAYMENT_METHOD);
    }

    private PaymentMethod(Name alias, Table<PaymentMethodRecord> aliased) {
        this(alias, aliased, null);
    }

    private PaymentMethod(Name alias, Table<PaymentMethodRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> PaymentMethod(Table<O> child, ForeignKey<O, PaymentMethodRecord> key) {
        super(child, key, PAYMENT_METHOD);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PAYMENT_METHOD_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<PaymentMethodRecord, Long> getIdentity() {
        return Keys.IDENTITY_PAYMENT_METHOD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PaymentMethodRecord> getPrimaryKey() {
        return Keys.PAYMENT_METHOD_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PaymentMethodRecord>> getKeys() {
        return Arrays.<UniqueKey<PaymentMethodRecord>>asList(Keys.PAYMENT_METHOD_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentMethod as(String alias) {
        return new PaymentMethod(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentMethod as(Name alias) {
        return new PaymentMethod(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PaymentMethod rename(String name) {
        return new PaymentMethod(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PaymentMethod rename(Name name) {
        return new PaymentMethod(name, null);
    }
}
