/*
 * This file is generated by jOOQ.
 */
package com.yg.gqlwfdl.dataaccess.db.tables;


import com.yg.gqlwfdl.dataaccess.db.Indexes;
import com.yg.gqlwfdl.dataaccess.db.Keys;
import com.yg.gqlwfdl.dataaccess.db.Public;
import com.yg.gqlwfdl.dataaccess.db.tables.records.PricingDetailsRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PricingDetails extends TableImpl<PricingDetailsRecord> {

    private static final long serialVersionUID = -878325275;

    /**
     * The reference instance of <code>public.pricing_details</code>
     */
    public static final PricingDetails PRICING_DETAILS = new PricingDetails();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PricingDetailsRecord> getRecordType() {
        return PricingDetailsRecord.class;
    }

    /**
     * The column <code>public.pricing_details.id</code>.
     */
    public final TableField<PricingDetailsRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('pricing_details_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.pricing_details.description</code>.
     */
    public final TableField<PricingDetailsRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.pricing_details.vat_rate</code>.
     */
    public final TableField<PricingDetailsRecord, Long> VAT_RATE = createField("vat_rate", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.pricing_details.discount_rate</code>.
     */
    public final TableField<PricingDetailsRecord, Long> DISCOUNT_RATE = createField("discount_rate", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.pricing_details.preferred_payment_method</code>.
     */
    public final TableField<PricingDetailsRecord, Long> PREFERRED_PAYMENT_METHOD = createField("preferred_payment_method", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>public.pricing_details</code> table reference
     */
    public PricingDetails() {
        this(DSL.name("pricing_details"), null);
    }

    /**
     * Create an aliased <code>public.pricing_details</code> table reference
     */
    public PricingDetails(String alias) {
        this(DSL.name(alias), PRICING_DETAILS);
    }

    /**
     * Create an aliased <code>public.pricing_details</code> table reference
     */
    public PricingDetails(Name alias) {
        this(alias, PRICING_DETAILS);
    }

    private PricingDetails(Name alias, Table<PricingDetailsRecord> aliased) {
        this(alias, aliased, null);
    }

    private PricingDetails(Name alias, Table<PricingDetailsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> PricingDetails(Table<O> child, ForeignKey<O, PricingDetailsRecord> key) {
        super(child, key, PRICING_DETAILS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PRICING_DETAILS_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<PricingDetailsRecord, Long> getIdentity() {
        return Keys.IDENTITY_PRICING_DETAILS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PricingDetailsRecord> getPrimaryKey() {
        return Keys.PRICING_DETAILS_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PricingDetailsRecord>> getKeys() {
        return Arrays.<UniqueKey<PricingDetailsRecord>>asList(Keys.PRICING_DETAILS_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PricingDetails as(String alias) {
        return new PricingDetails(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PricingDetails as(Name alias) {
        return new PricingDetails(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PricingDetails rename(String name) {
        return new PricingDetails(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PricingDetails rename(Name name) {
        return new PricingDetails(name, null);
    }
}
