/*
 * This file is generated by jOOQ.
 */
package com.yg.gqlwfdl.dataaccess.db.tables.records;


import com.yg.gqlwfdl.dataaccess.db.tables.OrderLine;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderLineRecord extends UpdatableRecordImpl<OrderLineRecord> implements Record3<Long, Long, Long> {

    private static final long serialVersionUID = 161295754;

    /**
     * Setter for <code>public.order_line.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.order_line.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.order_line.order</code>.
     */
    public void setOrder(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.order_line.order</code>.
     */
    public Long getOrder() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.order_line.product</code>.
     */
    public void setProduct(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.order_line.product</code>.
     */
    public Long getProduct() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, Long, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return OrderLine.ORDER_LINE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return OrderLine.ORDER_LINE.ORDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return OrderLine.ORDER_LINE.PRODUCT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getProduct();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getProduct();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderLineRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderLineRecord value2(Long value) {
        setOrder(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderLineRecord value3(Long value) {
        setProduct(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderLineRecord values(Long value1, Long value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrderLineRecord
     */
    public OrderLineRecord() {
        super(OrderLine.ORDER_LINE);
    }

    /**
     * Create a detached, initialised OrderLineRecord
     */
    public OrderLineRecord(Long id, Long order, Long product) {
        super(OrderLine.ORDER_LINE);

        set(0, id);
        set(1, order);
        set(2, product);
    }
}
